### ISSUE TITLE
latest version  hash

### ISSUE THREAD

**Issue by maromameta** [xiongnemo/blue-archive-jp-assets-downloader#1]
thanks for great code.
If you don't mind, could you please tell me how to get the latest version of the random hash(like r50_d561ioydiypbrigv2h6a)?

**Comment by xiongnemo** [comment]
> thanks for great code. If you don't mind, could you please tell me how to get the latest version of the random hash(like r50_d561ioydiypbrigv2h6a)?

BA Japanese seems to hardcode the version hash in their application package (not like global version), but I haven't figured out a way to directly extract the hash.

The hash is extracted by sniffering (Stream, Surge on iOS, for me I used Stream) traffic between the app and server:

![image](https://user-images.githubusercontent.com/38759782/210320866-05f03326-a219-478f-82b5-c01851391117.png)

For more info you may refer to [here](https://github.com/lwd-temp/blue-archive-spine#about-japan-version).

**Comment by maromameta** [comment]
thank you.
I will try to do a lot of things with reference to it.
