### ISSUE TITLE
只能下载apk而无法下载obb数据包

### ISSUE THREAD

**Issue by feilongproject** [xiongnemo/blue-archive-jp-assets-downloader#2]
日服目前安装包是由apk+obb(apks)组合而成, 如果只有apk而没有obb的话会报错

**Comment by xiongnemo** [comment]
> 日服目前安装包是由apk+obb(apks)组合而成, 如果只有apk而没有obb的话会报错

虽然似乎不属于这个 repo 的范畴，但还是写了。请参照 `[download_latest_obb.py](https://github.com/xiongnemo/blue-archive-jp-assets-downloader/blob/master/download_latest_obb.py)`
