### ISSUE TITLE
Table zip file encryption

### ISSUE THREAD

**Issue by viliml** [xiongnemo/blue-archive-jp-assets-downloader#3]
Do you know the password?

**Comment by xiongnemo** [comment]
> Do you know the password?

Currently, no.

I can't unpack these zips of table bundles using Global's password generation method (xxhash), so I believe they adopted a different approach.

**Comment by xiongnemo** [comment]
Solved in https://github.com/xiongnemo/blue-archive-jp-assets-downloader/commit/f3c0454d6bd597f76a119511a5e2a5f3db7971dd
